version: '2'
services:
  jna-compiler:
    build:
      context: .
    image: defreitas/jna-examples:latest
    volumes:
      - ./:/app
    working_dir: /app
    #command: ./gradlew clean build
    command: tail -f /dev/null
    network_mode: bridge
